/*
 * Copyright 2026 PicturePlayer;Nserly
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package top.nserly.PicturePlayer.NComponent.Frame;

import top.nserly.GUIStarter;
import top.nserly.PicturePlayer.NComponent.Component.PaintPicturePanel;
import top.nserly.PicturePlayer.Size.SizeOperate;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FullScreenFrame extends JFrame {
    private JPanel panel1;
    private PaintPicturePanel.ImageCanvas imageCanvas;

    public FullScreenFrame() {
        init();
    }

    public FullScreenFrame(PaintPicturePanel.ImageCanvas imageCanvas) {
        init();
        setImageCanvas(imageCanvas);
    }

    private void init() {
        setIconImage(GUIStarter.SOFTWARE_FRAME_ICON);
        setUndecorated(true);
        setSize(SizeOperate.FreeOfScreenSize);
        getContentPane().add(panel1);
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                if (!isShowing()) return;
                PaintPicturePanel.paintPicture.sizeOperate.incomeWindowDimension(imageCanvas.getSize());
                PaintPicturePanel.paintPicture.sizeOperate.update(false);
            }
        });
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                PaintPicturePanel.paintPicture.imageCanvas.setFullScreen(false);
            }
        });
    }

    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible && imageCanvas != null) {
            imageCanvas.requestFocusInWindow();
            imageCanvas.repaint();
        }
    }

    public void setImageCanvas(PaintPicturePanel.ImageCanvas imageCanvas) {
        if (imageCanvas == null) return;
        if (this.imageCanvas != null)
            panel1.remove(this.imageCanvas);
        this.imageCanvas = imageCanvas;
        panel1.add(imageCanvas, BorderLayout.CENTER);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
