package top.nserly.PicturePlayer.NComponent.Component;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Getter;
import lombok.Setter;
import top.nserly.GUIStarter;
import top.nserly.PicturePlayer.Loading.Bundle;
import top.nserly.PicturePlayer.Utils.ImageManager.Info.GetImageInformation;
import top.nserly.PicturePlayer.Utils.ImageManager.Info.ImageDPI;
import top.nserly.PicturePlayer.Utils.ImageManager.Info.ImageHandle;
import top.nserly.PicturePlayer.Utils.Window.WindowLocation;
import top.nserly.SoftwareCollections_API.FileHandle.ComputeFileSize;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Method;
import java.util.Locale;
import java.util.ResourceBundle;

public class PictureInformationViewer extends JDialog {
    private static Method $$$cachedGetBundleMethod$$$ = null;
    private JPanel panel1;
    private JTextField PictureNameTextField;
    private JLabel PictureSizeInfoLabel;
    private JLabel PictureTypeInfoLabel;
    private JLabel PictureResolutionInfoLabel;
    private JLabel PictureDPIInfoLabel;
    private JLabel PictureBitDepthInfoLabel;
    private JLabel PicturePathInfoLabel;
    private JScrollPane MainPanel;
    @Getter
    private String picturePath;

    public PictureInformationViewer(Frame owner) {
        super(owner, true);
        this.owner = owner;
        SwingUtilities.invokeLater(() -> {
            setTitle(Bundle.getMessage("PictureViewer_Title"));
            setIconImage(GUIStarter.SOFTWARE_FRAME_ICON);
            setLayout(new BorderLayout());
            add(MainPanel, BorderLayout.CENTER);
            setSize(630, 350);
            PictureNameTextField.addActionListener(e -> {

            });
        });
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            setLocation(WindowLocation.componentCenter(owner, getWidth(), getHeight()));
        }
        super.setVisible(visible);
    }

    /**
     * Updates the information displayed in the PictureInformationViewer with details from the provided image.
     *
     * @param imageHandle the ImageHandle object containing the image path, ImageReader, and ImageInputStream
     * @throws IOException if an I/O error occurs while processing the image
     */
    public synchronized void update(ImageHandle imageHandle) throws IOException {
        picturePath = imageHandle.path();
        File file = new File(picturePath);
        Dimension resolution = GetImageInformation.getImageResolution(imageHandle.imageReader());
        final ImageDPI DPI = GetImageInformation.getImageDPI(imageHandle.imageReader());
        final float AverageDPI = (DPI.HorizontalDPI() + DPI.VerticalDPI()) / 2;
        PictureNameTextField.setText(file.getName());
        PictureSizeInfoLabel.setText(ComputeFileSize.formatFileSize(ComputeFileSize.computeFileSize(file, 2)));
        PictureTypeInfoLabel.setText(GetImageInformation.getImageType(imageHandle.imageReader()));
        PictureResolutionInfoLabel.setText(resolution.width + " x " + resolution.height);
        PictureDPIInfoLabel.setText(AverageDPI + " dpi");
        PictureBitDepthInfoLabel.setText(GetImageInformation.getBitDepth(imageHandle.path()) + " bit");
        PicturePathInfoLabel.setText(file.getAbsolutePath());
    }
    @Setter
    private Frame owner;

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JScrollPane();
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(9, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setRequestFocusEnabled(false);
        MainPanel.setViewportView(panel1);
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(8, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, -1, 12, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_PictureNameLabel"));
        panel1.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, -1, 20, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label2, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_Title"));
        panel1.add(label2, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PictureNameTextField = new JTextField();
        PictureNameTextField.setRequestFocusEnabled(false);
        panel1.add(PictureNameTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, -1, 12, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label3, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_PictureSizeLabel"));
        panel1.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PictureSizeInfoLabel = new JLabel();
        PictureSizeInfoLabel.setRequestFocusEnabled(false);
        PictureSizeInfoLabel.setText("");
        panel1.add(PictureSizeInfoLabel, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, -1, 12, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label4, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_PictureTypeLabel"));
        panel1.add(label4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PictureTypeInfoLabel = new JLabel();
        PictureTypeInfoLabel.setRequestFocusEnabled(false);
        PictureTypeInfoLabel.setText("");
        panel1.add(PictureTypeInfoLabel, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label5, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_PictureResolutionLabel"));
        panel1.add(label5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PictureResolutionInfoLabel = new JLabel();
        PictureResolutionInfoLabel.setRequestFocusEnabled(false);
        PictureResolutionInfoLabel.setText("");
        panel1.add(PictureResolutionInfoLabel, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$(null, -1, 12, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label6, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_PictureDPILabel"));
        panel1.add(label6, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label7, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_PictureBitDepth"));
        panel1.add(label7, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PictureDPIInfoLabel = new JLabel();
        PictureDPIInfoLabel.setRequestFocusEnabled(false);
        PictureDPIInfoLabel.setText("");
        panel1.add(PictureDPIInfoLabel, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PictureBitDepthInfoLabel = new JLabel();
        PictureBitDepthInfoLabel.setRequestFocusEnabled(false);
        PictureBitDepthInfoLabel.setText("");
        panel1.add(PictureBitDepthInfoLabel, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setRequestFocusEnabled(false);
        this.$$$loadLabelText$$$(label8, this.$$$getMessageFromBundle$$$("messages", "PictureInfoViewer_PicturePathLabel"));
        panel1.add(label8, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PicturePathInfoLabel = new JLabel();
        PicturePathInfoLabel.setRequestFocusEnabled(false);
        PicturePathInfoLabel.setText("");
        panel1.add(PicturePathInfoLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
